Kartlar = {
"FİİL","İş","Oluş","Hareket","Eylem","Sözcük",
"HECE","Kelime","Harf","Ses","Okumak","Yazı",
"KÜSMEK","Darılmak","Kızmak","Konuşmak","Tartışmak","Kavga",
"AVİZE","Lamba","Kristal","Tavan","Işık","Aydınlık",
"KOORDİNAT","Yer","Enlem","Boylam","Belirtmek","Vermek",
"TERİM","Kelime","Anlam","Fatih","Sanat","Kavram",
"SOYUT","Duyu","Algılamak","Görülmeyen","İsim","Somut",
"BASKÜL","Tartı","Kilo","Ağır","Ölçü","Hafif",
"HALÜSİNASYON","Hayal","Gerçek","Görmek","İllüzyon","Serap",
"ARMAĞAN","Hediye","Vermek","Almak","Doğum günü","Sevindirmek",
"ANTİKA","Müzayede","Zengin","Eski","Tablo","Tarihi",
"ADEM ELMASI","Erkek","Gırtlak","Çıkıntı","Boğaz","Havva",
"SATRANÇ","Şah-Mat","Kale","Vezir","Piyon","Fil",
"PARAŞÜT","Uçak","Atlamak","Uçmak","Balon","Hava",
"TİYATRO","Oyuncu","Sahne","Perde","Oyun","Suflör",
"DOST","Güven","Samimi","Dürüst","Arkadaş","Ahlaklı",
"ANAHTAR","Kilit","Metal","Kasa","Kapı","Çilingir",
"KEDİ","Pati","Fare","Tüy","Kuyruk","Hayvan",
"BONKÖR","Eli Açık","Cömert","Para","Gönlü Zengin","Harcamak",
"FİDAN","Ağaç","Büyümek","Küçük","Orman","Dikmek",
"PRATİK","Kolay","Zekâ","Çabuk","Hızlı","Çözüm",
"MESAİ","Saat","İş","Fazla","Akşam","Kalmak",
"AKROSTİŞ","Şiir","Mısra","İsim","İlk","Kıta",
"BAMBU","Sazlık","Mobilya","Ağaç","Masa","Sandalye",
"YABANİ","Vahşi","İlkel","Hayat","Orman","Hayvan",
"YELPAZE","Sıcak","Rüzgar","Yaz","Kadın","Sallamak",
"ÇUVAL","Torba","Doldurmak","Yem","Un","Koymak",
"AJANDA","Defter","İş","Yazmak","Gün","Toplantı",
"İŞTAH","Acıkmak","Kesilmek","Açmak","Lezzet","Yemek",
"İHALE","Belediye","Girmek","Açmak","Yolsuzluk","Kazanmak",
"HİLE","Aldatmak","Kandırmak","Oyun","Yapmak","Kumar",
"HALAY","Düğün","Çekmek","Oynamak","Mendil","Mahmut Tuncer",
"PLAKET","Ödül","Tören","Başarı","Vermek","Teşekkür",
"STAJ","Öğrenci","Çalışmak","Üniversite","Tecrübe","İş",
"TECRÜBE","İş","Kazanmak","Çalışmak","Deneyim","Yıl",
"MACUN","Cam","Pencere","Tutmak","Diş","Mesir",
"ÇAVDAR","Arpa","Tahıl","Buğday","Kepek","Ekmek",
"VERESİYE","Peşin","Borç","Satın Almak","Ödemek","Defter",
"PERFORMANS","Değerlendirme","Başarı","Ders","Ödev","Yüksek",
"MONOTON","Aynı","Sıkıcı","Sıradan","Benzer","Rutin",
"PORSİYON","Yemek","Tabak","Lokanta","Yarım","Restoran",
"SERVET","Kazanmak","Zenginlik","Mal","Mülk","Para",
"TABURE","Oturmak","Sandalye","Koltuk","Yemekhane","Sırt",
"ÇAMAŞIR","Kirli","Yıkamak","Makine","Deterjan","Giymek",
"MİÇO","Tayfa","Gemi","Kaptan","Deniz","Yardımcı",
"ESKİMO","Kutup","Buzul","Kar","Soğuk","Balık",
"HASIR","Sepet","Şapka","Plaj","Deniz","Sermek",
"BUKALEMUN","Hayvan","Renk","Kertenkele","Değişmek","Sürüngen",
"KONVOY","Araba","Gitmek","Dizilmek","Arka","Düğün",
"CEPHE","Savaş","Ordu","Asker","Saldırmak","Barış",
"ZİRAAT","Tarım","Çiftçi","Toprak","Hayvan","Banka",
"FABL","Hayvan","La Fontaine","Masal","İnsan","Hikaye",
"MECAZ","Kelime","Sözcük","Gerçek","Anlam","Terim",
"ÖZNE","Cümle","İş","Kişi","Varlık","Öge",
"FAY","Hat","Deprem","Kırılmak","Sarsılmak","İstanbul",
"VARSAYIM","Olmamış","Tut ki","Farz et","Diyelim","Cümle",
"PARAGRAF","Sınav","Soru","Ana düşünce","Yardımcı düşünce","Metin",
"ÜÇ NOKTA","Noktalama","Son","Tamamlanmamış","İstenmeyen","Cümle",
"UYAK","Şiir","Dize","Benzerlik","Kafiye","Ses",
"SÖZLÜK","Anlam","Kelime","Sözcük","Açıklama","Lügat",
"OKKA","Ağırlık","Ölçü","Birim","Kilo","Tartı",
"MASAL","Olağanüstü","Kahraman","Yazar","Keloğlan","Kitap",
"ÖNERİ","Teklif","Çözüm","Yol","Cümle","İyi olur",
"İKİLEM","Kararsız","Cümle","Durum","Acaba","Tercih",
"BENZETME","Benzeyen","Benzetilen","Gibi","Güçlü","Güçsüz",
"ÖDEV","Okul","Öğretmen","Ders","Çalışmak","Ev",
"FAX","Çekmek","Yazı","Kağıt","Fotokopi","Göndermek",
"YARDIM","Bağış","Kızılay","İlk","Destek","Yapmak"
"DENEY","Kimya","Laboratuvar","Fare","Tüp","Bilim",
"ŞATAFAT","Gösterişli","Görkem","İhtişam","Çarpıcı","Süs",
"ZAMİR","İsim","Kişi","Adıl","İşaret","Kelime",
"NOKTA","Son","İşaret","Tarih","Cümle","Saat",
"AHESTE","Yavaş","Ağır","Hızlı","Tembel","Durgun"
}
